server:
  port: 18080
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
      name: auth-module
  datasource:
    name: mytest
    url: jdbc:mysql://127.0.0.1:3306/springboot?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
#    mysql 8.0.x
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    poolPreparedStatements: true

#redis配置
  redis:
      host: 127.0.0.1
      port: 6379
      password: redis-1.0
      timeout: 15000ms
      pool:
        min-idle: 0
        max-idle: 18
        max-active: 18
        timeout: 15000
        expire: 600

  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      timezone: GMT+8



mybatis-plus:
  mapperLocations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.qsq.auth.po
  global-config:
    db-config:
      column-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
#      table-prefix: ssm_
    refresh: true
  # mybatis 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  config: classpath:config/log4j2-dev.xml
  path: log



jwt:
  #长度不能太小
  secret: qsqbbbcccdddeeefffggghhhiiijjjkkklllmmmnnnooopppqqqrrrsssttt
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600
