server:
  port: 19000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        为服务整合控制台
    sentinel:
      transport:
        dashboard: localhost:8080
  application:
      name: order-module
  datasource:
    name: mytest
    url: jdbc:mysql://127.0.0.1:3306/springboot?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
#    mysql 8.0.x
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    poolPreparedStatements: true
mybatis-plus:
  mapperLocations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.qsq.order.po
  global-config:
    db-config:
      column-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
#      table-prefix: ssm_
    refresh: true
  # mybatis \u539F\u59CB\u914D\u7F6E
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  config: classpath:config/log4j2-dev.xml
  path: log



# actuator的配置
management:
  endpoints:
    web:
      exposure:
        include: '*'

#
jwt:
  #长度不能太小
  secret: qsqbbbcccdddeeefffggghhhiiijjjkkklllmmmnnnooopppqqqrrrsssttt
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600
